import type { ContratoColumnDefinition, ContratoFilters } from "./contractQuery.types";

// Define as colunas disponiveis na grade e sua ordem inicial.
export const contratoColumns: ContratoColumnDefinition[] = [
  { id: "tipoDocumento", label: "Tipo Documento", active: true },
  { id: "codMunicipio", label: "Municipio", active: true },
  { id: "cpfGestor", label: "CPF Gestor", active: true },
  { id: "numeroContrato", label: "Numero", active: true },
  { id: "dataAssinatura", label: "Data Assinatura", active: true },
  { id: "tipoObjeto", label: "Tipo Objeto", active: true },
  { id: "modalidade", label: "Modalidade", active: true },
  { id: "cpfGestorOriginal", label: "CPF Gestor Original", active: false },
  { id: "numeroContratoOrig", label: "Numero Contrato Original", active: false },
  { id: "dataContratoOrig", label: "Data Contrato Original", active: false },
  { id: "vigenciaInicial", label: "Vigencia Inicial", active: true },
  { id: "vigenciaFinal", label: "Vigencia Final", active: true },
  { id: "dataInicioObra", label: "Data Inicio Obra", active: false },
  { id: "tipoObraServico", label: "Tipo Obra/Servico", active: false },
  { id: "numeroObra", label: "Numero Obra", active: false },
  { id: "dataTerminoObra", label: "Data Termino Obra", active: false },
  { id: "referencia", label: "Referencia", active: true },
  { id: "dataAutuacao", label: "Data Autuacao", active: false },
  { id: "numeroProcesso", label: "Numero Processo", active: false },
  { id: "valor", label: "Valor", active: true },
  { id: "objeto", label: "Objeto", active: true },
  { id: "cpfFiscal", label: "CPF Fiscal", active: true },
  { id: "nomeFiscal", label: "Nome Fiscal", active: true },
  { id: "idContratoPncp", label: "Id Contrato PNCP", active: false },
];

// Mantem o formato padrao dos filtros locais da grade.
export const emptyFilters: ContratoFilters = {
  tipoDocumento: "",
  numeroContrato: "",
  dataAssinatura: "",
  tipoObjeto: "",
  modalidade: "",
  codMunicipio: "",
  cpfGestor: "",
  cpfGestorOriginal: "",
  numeroContratoOrig: "",
  dataContratoOrig: "",
  vigenciaInicial: "",
  vigenciaFinal: "",
  dataInicioObra: "",
  tipoObraServico: "",
  numeroObra: "",
  dataTerminoObra: "",
  referencia: "",
  dataAutuacao: "",
  numeroProcesso: "",
  valor: "",
  objeto: "",
  cpfFiscal: "",
  nomeFiscal: "",
  idContratoPncp: "",
};
