// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410002112_InclusaoLicitacao")]
    partial class InclusaoLicitacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_municipio");

                    b.Property<string>("CpfFiscal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_fiscal");

                    b.Property<string>("CpfGestor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_gestor");

                    b.Property<string>("CpfGestorOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_gestor_original");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime?>("DataAutuacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_autuacao");

                    b.Property<DateTime?>("DataContratoOrig")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_contrato_original");

                    b.Property<DateTime?>("DataInicioObra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_obra");

                    b.Property<DateTime?>("DataTerminoObra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_termino_obra");

                    b.Property<string>("IdContratoPncp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_contrato_pncp");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("NomeFiscal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_fiscal");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_contrato");

                    b.Property<string>("NumeroContratoOrig")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_contrato_original");

                    b.Property<string>("NumeroObra")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_obra");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_processo");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objeto_contrato");

                    b.Property<DateTime?>("Referencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("referencia");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoObjeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_objeto");

                    b.Property<string>("TipoObraServico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_obra_servico");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<DateTime?>("VigenciaFinal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_final");

                    b.Property<DateTime?>("VigenciaInicial")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicial");

                    b.HasKey("Id");

                    b.ToTable("contratos");
                });

            modelBuilder.Entity("Domain.Entities.Licitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_municipio");

                    b.Property<string>("CpfCotacaoPrecos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_cotacao_precos");

                    b.Property<string>("CpfElaboradorTermo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_elaborador_termo");

                    b.Property<string>("CpfGestorUnidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_gestor_unidade");

                    b.Property<string>("CpfHomologacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_homologacao");

                    b.Property<string>("CpfParecerJuridico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_parecer_juridico");

                    b.Property<string>("CriterioJulgamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criterio_julgamento");

                    b.Property<DateTime?>("DataAutuacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_autuacao");

                    b.Property<DateTime?>("DataHomologacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_homologacao");

                    b.Property<DateTime?>("DataPortariaComissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_portaria_comissao");

                    b.Property<DateTime?>("DataRealizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_realizacao");

                    b.Property<DateTime?>("DataReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_referencia");

                    b.Property<string>("EspecieProcesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especie_processo");

                    b.Property<string>("FormaContratacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_contratacao");

                    b.Property<string>("FundamentacaoLegal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fundamentacao_legal");

                    b.Property<string>("HoraRealizacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hora_realizacao");

                    b.Property<string>("IdAtaPncp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_ata_pncp");

                    b.Property<string>("IdContratacaoPncp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_contratacao_pncp");

                    b.Property<string>("JustificativaPreco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("justificativa_preco");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("MotivoEscolhaFornecedor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo_escolha_fornecedor");

                    b.Property<string>("NomeCotacaoPrecos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_cotacao_precos");

                    b.Property<string>("NomeElaboradorTermo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_elaborador_termo");

                    b.Property<string>("NomeHomologacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_homologacao");

                    b.Property<string>("NomeParecerJuridico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_parecer_juridico");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_processo");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objeto");

                    b.Property<string>("OrgaoGerenciadorAta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("orgao_gerenciador_ata");

                    b.Property<string>("SequencialComissao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sequencial_comissao");

                    b.Property<string>("SistemaRegistroPreco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sistema_registro_preco");

                    b.Property<string>("TipoDisputa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_disputa");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("UrlPlataforma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_plataforma");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_estimado");

                    b.Property<decimal>("ValorLimiteSuperior")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_limite_superior");

                    b.HasKey("Id");

                    b.ToTable("licitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
