// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408170333_IncluirReferenciaContratos")]
    partial class IncluirReferenciaContratos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_municipio");

                    b.Property<string>("CpfFiscal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_fiscal");

                    b.Property<string>("CpfGestor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_gestor");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_assinatura");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("NomeFiscal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_fiscal");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_contrato");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objeto_contrato");

                    b.Property<DateTime?>("Referencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("referencia");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_documento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<DateTime?>("VigenciaFinal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_final");

                    b.Property<DateTime?>("VigenciaInicial")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicial");

                    b.HasKey("Id");

                    b.ToTable("contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
